name: Deployment to the cluster

on: [push]
jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API"
        run: |
          pwd
          ls -lh
          ls -lh *.yml
