name: Deployment to the cluster

on:
  schedule:
    - cron: '45 17 * * *'
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Call the cluster API"
        run: pwd
      - name: "Call the cluster API"
        run: ls -lha
      - name: "Call the cluster API"
        run: ls -lha *.yml
