name: Deployment to the cluster

on:
  schedule:
    - cron: '45 17 * * *'
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: "Call the cluster API"
        shell: bash
        env:
          cluster_api_login: ${{ secrets.cluster_api_login }}
          cluster_api_password: ${{ secrets.cluster_api_password }}
        run: |
          set -e
          for file in *.yml
          do
            curl --silent --fail-with-body -X POST --data-binary "@$file" https://$cluster_api_login:$cluster_api_password@c2.krato.cz/deploy/"${file%.*}"
          done
